AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Publish Data S3 Staging

Parameters:
  BucketName:
    Type: String
    Default: mytiki-publish
    Description: Enter the S3 bucket name for staging.
  NotificationQueue:
    Type: String
    Description: The name of the queue to aggregate s3 notifications
    Default: publish-data-load

Resources:
  #  Queue:
  #    Type: AWS::SQS::Queue
  #    Properties:
  #      QueueName: !Ref NotificationQueue

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
#        QueueConfigurations:
#          - Event: s3:ObjectCreated:*
#            Queue: !GetAtt Queue.Arn
#            Filter:
#              S3Key:
#                Rules:
#                  - Name: prefix
#                    Value: loady/

#  QueuePolicy:
#    Type: AWS::SQS::QueuePolicy
#    Properties:
#      PolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service: s3.amazonaws.com
#            Action: SQS:SendMessage
#            Resource: !GetAtt Queue.Arn
#            Condition:
#              ArnLike:
#                aws:SourceArn: !GetAtt Bucket.Arn
#              StringEquals:
#                aws:SourceAccount: !Ref AWS::AccountId
#      Queues:
#        - !Ref Queue
